name = "La Cacería Secreta"
source_code_url = "https://github.com/DeltaZen/la-caceria-secreta"

[store]
id="com.github.DeltaZen.lacaceriasecreta"
version_name=1.0
version_code=1
author="M4ss1ck"
author_email="massick@systemli.org"
description="Aventura ambientada en el mundo de Tramórea"